cvmaster00 replaced by master00 in requests and configurations

diff --git a/calvalus-experiments/tradeoff-analysis/analyseprocessinglogs b/calvalus-experiments/tradeoff-analysis/analyseprocessinglogs
--- a/calvalus-experiments/tradeoff-analysis/analyseprocessinglogs
+++ b/calvalus-experiments/tradeoff-analysis/analyseprocessinglogs
@@ -11,12 +11,12 @@ fi
 
 jobnumber="$1"
 
-# 2010-10-13 18:33:21,607 INFO cvmaster00 Initializing job_201010081626_0022
-# 2010-10-13 18:33:58,000 INFO cvmaster00 Job job_201010081626_0022 has completed successfully.
+# 2010-10-13 18:33:21,607 INFO master00 Initializing job_201010081626_0022
+# 2010-10-13 18:33:58,000 INFO master00 Job job_201010081626_0022 has completed successfully.
 
-job_start=`cat ${jobnumber}.log | awk '/cvmaster00 Initializing job_/ { print $1, $2 }' | head -1`
-job_stop=`cat ${jobnumber}.log | awk '/cvmaster00 Job job_.* has completed successfully./ { print $1, $2 }'`
-job_abort=`cat ${jobnumber}.log | awk '/cvmaster00 Aborting job_.*/ { print $1, $2 }'`
+job_start=`cat ${jobnumber}.log | awk '/master00 Initializing job_/ { print $1, $2 }' | head -1`
+job_stop=`cat ${jobnumber}.log | awk '/master00 Job job_.* has completed successfully./ { print $1, $2 }'`
+job_abort=`cat ${jobnumber}.log | awk '/master00 Aborting job_.*/ { print $1, $2 }'`
 
 echo "${job_start} start ${jobnumber}" > ${jobnumber}.list.tmp
 if [ "job_stop" != "" ]
@@ -26,31 +26,31 @@ else
     echo "${job_abort} abort ${jobnumber}" >> ${jobnumber}.list.tmp
 fi
 
-# 2010-10-13 18:33:24,976 INFO cvmaster00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
+# 2010-10-13 18:33:24,976 INFO master00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
 
-attempts=`cat ${jobnumber}.log | awk '/cvmaster00 Adding task .attempt_([0-9_]*)/ { print substr($7,10,length($7)-10) }'`
+attempts=`cat ${jobnumber}.log | awk '/master00 Adding task .attempt_([0-9_]*)/ { print substr($7,10,length($7)-10) }'`
 
 for attempt in ${attempts}
 do
     task=${attempt%_[0-9]}
     echo "attempt ${attempt}"
 
-# 2010-10-13 18:33:24,976 INFO cvmaster00 Choosing data-local task task_201010081626_0022_m_000001
-# 2010-10-13 18:33:24,976 INFO cvmaster00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
-# 2010-10-13 18:33:33,983 INFO cvmaster00 Task 'attempt_201010081626_0022_m_000001_0' has completed task_201010081626_0022_m_000001 successfully.
-# 2010-10-13 18:33:24,976 INFO cvmaster00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
-# 2010-10-20 09:13:53,900 INFO cvmaster00 tip:task_201010081626_0048_m_000002 has split on node:/default-rack/cvslave04.bc.local
+# 2010-10-13 18:33:24,976 INFO master00 Choosing data-local task task_201010081626_0022_m_000001
+# 2010-10-13 18:33:24,976 INFO master00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
+# 2010-10-13 18:33:33,983 INFO master00 Task 'attempt_201010081626_0022_m_000001_0' has completed task_201010081626_0022_m_000001 successfully.
+# 2010-10-13 18:33:24,976 INFO master00 Adding task 'attempt_201010081626_0022_m_000001_0' to tip task_201010081626_0022_m_000001, for tracker 'tracker_cvslave04.bc.local:localhost/127.0.0.1:48991'
+# 2010-10-20 09:13:53,900 INFO master00 tip:task_201010081626_0048_m_000002 has split on node:/default-rack/cvslave04.bc.local
 
-    if ! grep -q "cvmaster00 Choosing .* task task_${task}" ${jobnumber}.log
+    if ! grep -q "master00 Choosing .* task task_${task}" ${jobnumber}.log
     then
         continue
     fi
 
-    task_start=`cat ${jobnumber}.log | awk "/cvmaster00 Adding task .attempt_${attempt}/ { print \\$1, \\$2 }"`
-    task_stop=`cat ${jobnumber}.log | awk "/cvmaster00 Task .attempt_${attempt}. has completed .* successfully./ { print \\$1, \\$2 }"`
+    task_start=`cat ${jobnumber}.log | awk "/master00 Adding task .attempt_${attempt}/ { print \\$1, \\$2 }"`
+    task_stop=`cat ${jobnumber}.log | awk "/master00 Task .attempt_${attempt}. has completed .* successfully./ { print \\$1, \\$2 }"`
     task_abort=`cat ${jobnumber}.log | awk "/cvslave..  About to purge task: attempt_${attempt}/ { print \\$1, \\$2 }"`
-    task_host=`cat ${jobnumber}.log | awk "/cvmaster00 Adding task .attempt_${attempt}/ { print substr(\\$13,10,9) }"`
-    if grep -q "cvmaster00 tip:task_${task} has split on node:/default-rack/${task_host}" ${jobnumber}.log
+    task_host=`cat ${jobnumber}.log | awk "/master00 Adding task .attempt_${attempt}/ { print substr(\\$13,10,9) }"`
+    if grep -q "master00 tip:task_${task} has split on node:/default-rack/${task_host}" ${jobnumber}.log
     then
         task_local=data_local
     else
@@ -67,9 +67,9 @@ do
     task_done=`cat ${jobnumber}.log | awk "/cvslave..  Task attempt_${attempt}_. is done/ { print \\$1, \\$2 }"`
     task_removed=`cat ${jobnumber}.log | awk "/cvslave..  attempt_${attempt}_. done; removing files/ { print \\$1, \\$2 }"`
 
-# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://cvmaster00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
-# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://cvmaster00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
-# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://cvmaster00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
+# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://master00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
+# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://master00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
+# 2010-10-14 16:28:58,524 INFO cvslave05  attempt_201010081626_0031_m_000010_0 starts processing of split hdfs://master00:9000/user/boe/meris-l1/MER_RR__1PQACR20040526_091235_000026432027_00122_11699_0000.N1:201311116+17000857 (5321+457)
 
     map_start=`cat ${jobnumber}.log | awk "/^20.*cvslave..  attempt_${attempt} starts processing of split/ { print \\$1, \\$2 }" | head -1`
     map_stop=`cat ${jobnumber}.log | awk "/^20.*cvslave..  attempt_${attempt} stops processing of split/ { print \\$1, \\$2 }" | head -1`
