fix errros in granule splitting script

diff --git a/calvalus-examples/bundles/s2-granules-1.0/granule-splitter-process b/calvalus-examples/bundles/s2-granules-1.0/granule-splitter-process
--- a/calvalus-examples/bundles/s2-granules-1.0/granule-splitter-process
+++ b/calvalus-examples/bundles/s2-granules-1.0/granule-splitter-process
@@ -3,13 +3,12 @@
 # switch on job control
 set -e
 set -m
-set -o pipefail
 
 . /etc/profile
 
 counter=0
 
-num_granules=$(unzip -l ${1}|grep -E "GRANULE.*_[0-9]{8}T[0-9]{6}$"|wc -l)
+num_granules=$(unzip -l ${1}|grep -E "GRANULE/.*_T[0-9]{2}[A-Z]{3}.xml"|wc -l)
 echo "num_granules: ${num_granules}"
 
 function handle_stdout() {
@@ -19,9 +18,11 @@ function handle_stdout() {
     outputfilename=${BASH_REMATCH[1]}
     echo CALVALUS_OUTPUT_PRODUCT $(basename ${outputfilename})
 
-    counter=$((counter+1))
-    progress=$(echo "scale=3; ${counter} / ${num_granules}" | bc)
-    printf "CALVALUS_PROGRESS %.3f\n" ${progress}
+    if [[ ${num_granules} != 0 ]]; then
+      counter=$((counter+1))
+      progress=$(echo "scale=3; ${counter} / ${num_granules}" | bc)
+      printf "CALVALUS_PROGRESS %.3f\n" ${progress}
+    fi
   fi
 }
 
@@ -30,6 +31,11 @@ function handle_stdout() {
 jar=calvalus-inventory*jar
 class=com.bc.calvalus.sentinel2.GranuleSplitter
 java -Xmx265M -cp ${jar} ${class} ${1} . | while read x ; do handle_stdout "$x" ; done
+
+if [[ ${PIPESTATUS[0]} != 0 ]]; then
+  echo "error calling GranuleSplitter"
+  exit ${PIPESTATUS[0]}
+fi
 
 marker=_$(basename ${1})
 touch ${marker}
